### ISSUE TITLE
Account/Resource Provisioning Architecture

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder-technology-and-ux#10]
Create the work flow diagram and high level architecture for provisioning a storage instance.

Assumptions:
Start with DevHub Login
Populate meta data to tag storage instance with billing/branch info
Leverage Azure service account
Provision storage via Azure API
Return endpoint and keys for access

**Comment by sheaphillips** [comment]
I'm not sure that Dynamic365 will have the concept of an "instance" or if it is more like a "namespace" or "team", but we can definitely explore and see what the options are and how to map into an self-service provisioning model .

**Comment by kelpisland** [comment]
I'm going to generalize this ticket away from Dynamics 365 and focus on storage only for now.
