### ISSUE TITLE
Dev Knowledge base

### ISSUE THREAD

**Issue by kelpisland** [bcgov/cloud-pathfinder-technology-and-ux#102]
**Describe the issue**

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by lukegonis** [comment]
@sheaphillips can you please update/put it in the appropriate swim lane? thanks

**Comment by sheaphillips** [comment]
I'm going to leave this where it is (in Product Backlog) as we may pick it up later if we refine the conformance survey/wizard.  It's also fine if you want to move it to Closed (Dropped) and we can re-spec it if/when we pick it up.
