### ISSUE TITLE
Issues in (eventually) acquiring AWS landing zone code 

### ISSUE THREAD

**Issue by mumit** [bcgov/cloud-pathfinder-technology-and-ux#126]
**Describe the issue**
Answer the question if there are barriers to (eventual) publication of landing zone code.

**Which Sprint Priority is this issue related to?**

**Additional context**

**Definition of done**
Decision on whether we can or not (and if not, list the barriers)

**Comment by ActionAnalytics** [comment]
Waiting on AWS lawyers.  We've proposed bcgov-c and AWS tech team seems ok with this pending legal approval.
