### ISSUE TITLE
Resolve AWS SOW signature issue

### ISSUE THREAD

**Issue by mumit** [bcgov/cloud-pathfinder-technology-and-ux#137]
**Describe the issue**
Hayden's signature on SOW was flagged as out-of-focus by AWS, and has been re-routed via docusign for Hayden's electronic signature.

**Which Sprint Priority is this issue related to?**

**Additional context**
This is required for AWS ProServ to complete the current tasks.

**Definition of done**
When re-signed and accepted by AWS.

**Comment by mumit** [comment]
@lukegonis @kelpisland -- it's critical to resolve the signature issue now that Ricardo is almost done with the "basics". 

Luke -- please see the email thread with subject "RE: Signed SOW attached", originally from Nathan Klein@AWS, and I added you to the thread in my response.

**Comment by kelpisland** [comment]
@lukegonis  can you chase this down today.

**Comment by lukegonis** [comment]
@kelpisland @mumit Yes, I will follow up on this

**Comment by mumit** [comment]
Thanks. Please keep Nathan in the loop -- we don't want Ricardo to have to slow down his work with Shea on authn/authz.

**Comment by ateppin** [comment]
Emailed both Luke & Nathan with regards to this issue.

**Comment by ateppin** [comment]
Confirmed with Nathan Klein at AWS that the SoW had been signed.
