### ISSUE TITLE
Sample AWS app architecture

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#142]
We need to understand the platform infrastructure footprint/architecture of either BC Enhanced Travel and Farm Operator Screening apps in order to provision another one like them.

This relates to milestone 1. automated team access

**Additional context**
- https://github.com/bcgov/enhanced-travel-screening
- https://github.com/bcgov/Foreign-Farm-Workers-Permitting-System
- https://github.com/bcgov/silviculture-ipc

- A list of all the key pieces of such an app (list the accounts and properties, Cloud Provider infrastructure resources used (network, storage, w/e))
- Probably a mapping of what traditionally would have been tools/dev/test/prod environments/namespaces in openshift and are now present in AWS as accounts.  What are those accounts, what do they look like?
- Any KeyCloak pieces
- Identify vendor specific items with idea to port to other clouds but this is not the main focus, it is a nice to have at this point

**Comment by ateppin** [comment]
Reached out to a team member to see what they have available for architectural diagrams etc & a possible walk through

**Comment by ActionAnalytics** [comment]
https://github.com/bcgov/enhanced-travel-screening
- github actions deployment pipeline
- 2 node js servers
- dynamoDb service

https://github.com/bcgov/Foreign-Farm-Workers-Permitting-System
- github actions deployment pipeline
- 2 node js servers
- DocumentDb service / mongoDb

https://github.com/bcgov/silviculture-ipc  <-- running on Kamloops On-Prem OpenShift cluster
- github actions deployment pipeline
- node js API server
- Vue js front-end server
- postgreSQL
- Sequelise ORM
- morgan logging http request logging
- Metabase
- Axios Network caller
- KeyCloak auth

**Comment by ateppin** [comment]
Notes from Tim Csaky

Further information:
1- the Website and back-end API are both built using the Node JS framweork. The front-end uses the Vue JavaScript library and the API uses a Express JS (node, javascript) server.

2 - We're using Postgres databases with backups to the BC Govt. NFS storage

3 - authentication from the client and between the server components is handled by Keycloak

4 - The app includes a 'convert to PDF' feature which is handled by a BC Gov common component.
This is separate hosted microservice we have built in another namespace.
https://github.com/bcgov/common-document-generation-service

5 - email notifications are also handled by a separate common component:
https://github.com/bcgov/common-hosted-email-service

6 - We're able to provide reporting on data from each application using an SQL visualization tool called Metabase.
A snapshot of the Silviculture statistics can be seen here: https://metabase-wxpbtr-prod.pathfinder.gov.bc.ca/public/dashboard/650ce75d-6710-49ef-8ee7-1af2
b52e7a33
