### ISSUE TITLE
Review access setup for existing Google deployments

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#146]
**Describe the issue**
We need to see which BC Gov Google deployments are having the issue

**Which Sprint Priority is this issue related to?**
Milestone 2. Google Separation of Concerns
**Definition of done**
- A list of 2 or more Google accounts/environments/namespaces that are currently experiencing the problem of seeing resources that do not belong to them

**Comment by sheaphillips** [comment]
Note there is ongoing work being done by Arctiq in setting up the "landing zone".  I would suggest any work around GCP check in with that work stream, and also that we set up an overview session for the "current state" in GCP.  It's going to be messy otherwise.

**Comment by sheaphillips** [comment]
@ateppin @ActionAnalytics if we can get a summary of what problem/unexpected behaviour is (from @watkinspd ?), I can support this work if needed.

**Comment by lukegonis** [comment]
No longer a priority
