### ISSUE TITLE
Design rules around what should be visible/not

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#147]
**Describe the issue**
We need to know what resources if any a team should see or not see

**Which Sprint Priority is this issue related to?**
Milestone 2 Google setup

**Additional context**
Most likely it will be that nothing is visible, but there may be exceptions

**Definition of done**
- A list of exceptions if any that could be visible across projects in Google

**Comment by lukegonis** [comment]
no longer a priority/dropped
