### ISSUE TITLE
Create two Google projects that can't see each other's resources

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#148]
**Describe the issue**
We need to prove out the rules we came up with

**Which Sprint Priority is this issue related to?**
Milestone 2.  Google set up

**Additional context**

**Definition of done**
- 2 Demoable Google projects that conform to the new visibility rules

**Comment by lukegonis** [comment]
no longer a priority/dropped
