### ISSUE TITLE
Azure Tenancy Prereqs: Reach out to Scott & PJ

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#151]
**Describe the issue**
Confirm costs with Scott & PJ

**Which Sprint Priority is this issue related to?**
Milestone 3.  Azure Tenancy

**Additional context**

**Definition of done**
- make sure that the IP ownership is clearly defined as being us in SOW
- additional costs laid out before talking to Dwayne
- commitments for Microsoft resources (people's time to assist us)
- need readiness of tenancy (dates, what can be ready for us)

**Comment by ateppin** [comment]
Reached out to Scott & PJ for a status update on SoW costs.

**Comment by ateppin** [comment]
We (Julian, Stuart, Andy) met with Peter  (Thursday May 21) with details about MSFT engagement for Azure (pathfinder & ES phase 2).

Peter spoke to Dwayne (Friday May 22) to have alignment between our groups & they agreed on the need for a single SoW (& ask for money)

Julian, Stuart, Shea & I met with David Ell & Dennis Murch (Monday May 25) to discuss Dwayne's email about working together, the MSFT SoW & our requirements

**Comment by ateppin** [comment]
SoW updated (Julian, Stuart, Andy) on Thursday

Meeting this afternoon to include Ryan, Shea & Paul to review changes

**Comment by ateppin** [comment]
Final draft SoW back to MSFT for discussion Friday.

For this sprint, this ticket is done.
