### ISSUE TITLE
Azure Tenancy Prereqs: Present to Dwayne

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#152]
**Describe the issue**
We need to present our ask for Azure phase 2 to Dwayne so he can include it in the SOW

**Which Sprint Priority is this issue related to?**
Milestone 3. Azure Tenancy

**Additional context**
Touchpoint with Peter required before showing to Dwayne

**Definition of done**
- Provide information to Dwayne in an easy to understand format such that
- The ask we need can be included in the SOW

**Comment by ateppin** [comment]
May not be necessary as Peter talked to Dwayne & they're in agreement about alignment.

**Comment by ateppin** [comment]
We are having ongoing discussions about the SoW.  But this is captured in another ticket.
