### ISSUE TITLE
Provide PF team with access to AWS Exchange mailbox

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#156]
**Describe the issue**
We need to expand the use of mailboxes to manage our AWS Landing Zone

**Which Sprint Priority is this issue related to?**
Milestone 1

**Additional context**
We are transitioning to new people and have a new AWS billing notification that we wish to enable.

**Definition of done**
- Housekeeping: OCIO AWS Master Acccount CITZ:EX need to have the typo in the name fixed (Acccount to Account) 
- OCIO AWS Master Account CITZ:EX needs to have the following people permitted to receive messages: Julian, Stuart, Ryan
- Additional mailbox for AWS billing alerts created.  OCIO AWS Billing Account CITZ:EX with Luke, Andy, Julian, Stuart as recipients

**Comment by sheaphillips** [comment]
@lukegonis some pointers as you work through this ticket: most of this  involves twiddling/requesting access to Exchange email mailbox for additional team members.  I believe there are currently two mailboxes to deal with: 

- one where all account emails are funneled (em-cloud-pathfinder_at_gov.bc.ca or similar)
- another for the root account...not sure what this one is, but check with @ateppin 

For the "additional mailbox" item for billing...hold off on doing anything with that one as I believe it is related to another ticket of mine and I will LYK if there is anything for you to do.

**Comment by ateppin** [comment]
@lukegonis - the root account (OCIO AWS Master Account - ocio-aws-em-master@gov.bc.ca)

Can you also look at having the ownership changed from Todd to Julian (@ActionAnalytics )

**Comment by sheaphillips** [comment]
@lukegonis we should also be tracking "objects" (mailboxes in this case)
that cloud pathfinder manages/governs.  For Pathfinder, we had created an
"inventory" board of all the accounts and processes that we were involved
in.  For Cloud PF, we could do similar, or maybe do it in Documize?  Not
fussed, but I think it's important to take the opportunity to do this as we
transition

**Comment by ActionAnalytics** [comment]
FYI @bluemel-gov

**Comment by ActionAnalytics** [comment]
Pop is helping us reactivate the account that was slated to be cancelled on Todd's offboarding

**Comment by ActionAnalytics** [comment]
Looks like the mailbox got deleted.  Needs followup @lukegonis

**Comment by ActionAnalytics** [comment]
Andy T: Looks like I don’t have permission to access the mailbox anymore for ocio-a..-master@gov.bc.ca.

**Comment by ateppin** [comment]
You & me both.

**Comment by ateppin** [comment]
Talking to OCIO-ES about (OCIO AWS Master Account - ocio-aws-em-master@gov.bc.ca) which got deleted when Todd left.

Looking to bring it back & have the ownership changed to Julian.

**Comment by ateppin** [comment]
The account & mailbox should now be available again.  And the ownership should now be under Julian.

**Comment by ateppin** [comment]
Even though the account was reinstated & the mailbox reattached there were still some issues with access.

July 6 - I added Julian, Shea, Stuart with "ownership" level permissions.  

July 8 - Added Ryan with "reviewer" level permissions.
