### ISSUE TITLE
Setup for AWS Rich Text notifications

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#157]
**Describe the issue**
AWS has a new SES rich text email format that we wish to consume due to the increased readability.

**Which Sprint Priority is this issue related to?**
Milestone 1

**Additional context**
See email forwarded to Shea from Andy May 25 for details

**Definition of done**
- provide AWS what they need to make SES work
- team can begin receiving rich text notifications

**Comment by sheaphillips** [comment]
DNS set up for SES to work has been done.  I will create a new ticket for validation or follow on work related to email budget alerts, which is the business use case related to this.
