### ISSUE TITLE
Set up AWS budget notifications

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder-technology-and-ux#161]
**Describe the issue**
We need to receive electronic notifications when costs are approaching budget thresholds, etc.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Initial work has been done to enable this (turning on functions in AWS by AWS, and DNS changes required on BC Gov side).
Functionality has not been described or demonstrated yet.

**Definition of done**
- All users who need to receive alerts are "invited"/onboarded/email verified by Andy/Ryan (AWS)
- Sample/real notifications demonstrated to our team (by AWS)
- team has an approach for actioning future requests that come from the automation.

**Comment by ActionAnalytics** [comment]
Better to do this sooner so that it lightens our ongoing operational load

**Comment by ActionAnalytics** [comment]
Shea is not getting these yet
Stuart is not getting these

**Comment by ateppin** [comment]
Modified the Budget Alarms Notification to include Shea & Stuart.

The current list of notifications includes:
- Ryan Jaeger
- Andy Fase
- Julian Subda
- Shea Phillips
- Stuart Cayzer
- Andy Teppin

**Comment by sheaphillips** [comment]
We should check if there's a Terraform facility for setting up/managing
this, and we also want to peek at adding in  per-account budgets/alerts as
part of account creation automation.
