### ISSUE TITLE
Access to AWS landing zone code for security review

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder-technology-and-ux#163]
-- Objective
-- to review the security compliance of the landing zone against OCIO security practices and guidelines

- Def of Done
-- Access to the landing zone code
-- Review AWS landing zone code from security perspective with Shea/Julian 
- Provide finders
--  loop in Privacy( Holly) with findings

**Comment by ActionAnalytics** [comment]
Hi @bluemel-gov  let's break this down please.  An 8 is too big for getting access. 

Can you create some smaller tickets around 3 in size or smaller.

Is this still ongoing?

**Comment by bluemel-gov** [comment]
- re-scoped and re-opened ticket

**Comment by ActionAnalytics** [comment]
Need clearer DoD before approval for this work to continue.  What is the demo-able output of a review?
