### ISSUE TITLE
Create Demo Terraform Scripts

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder-technology-and-ux#169]
**Describe the issue**
to handle project space via AWS so that team via GitHub can self-serve triggered by the team 

Longer term: Project teams get an account (on Terraform Cloud) and choose which services, pull down as Module refs and call them from their pipeline in GitHub Actions, Tekton, Jenkins, or local CLI 

Might not expect us to come out with any modules from this effort 

However, Ryan Jaeger shared working Terraform Elastic Bean Stalk provisioning code with us 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
-deploys elastic beanstock resources
-can be called from a workspace

**Comment by ateppin** [comment]
Met with Ryan J from AWS to review his work.  Turns out he did not use Elastic Beanstalk, but a combination of other AWS services including Elastic Container Service (ECS), Fargate. AWS Secret Manager, DocumentDB etc.

**Comment by ActionAnalytics** [comment]
Broke out TF Cloud part into other tickets
