### ISSUE TITLE
Take ownership of AWS Services engagement

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder-technology-and-ux#172]
**Describe the issue**

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Establish a clear statement of the objective(s) of our work with AWS (definition of done) 
- Establish summary of work to date + what remains to be done 
- Confirm remaining SoW hours

**Comment by sheaphillips** [comment]
@ActionAnalytics please let me know if you'd like me to be involved in this.

**Comment by ateppin** [comment]
Contacted AWS (Nathan) for a break down of: work done to date, remaining hours & input for what they think we should use the remaining hours on.

**Comment by ateppin** [comment]
Details from the SoW:

*   Assist Customer with the review of the Customer’s current environment, designs, and patterns to provide best practices recommendations.
*   Assist Customer with a review of its AWS account strategy to address governance, billing, compliance, and other environment isolation requirements.
*   Provide Customer with information on general best practices and guidance on AWS account creation and Identity and Access Management (IAM) policy definitions.
*   Assist Customer with the development of a foundational Landing Zone environment and associated resources such as shared services, consolidated billing, consolidated security logging, and any defined application lifecycles (e.g. Development, Test, Production, Sandbox).
*   Provide Customer with recommendations on core infrastructure and security controls in a multi-account and multi-region AWS environment.

In conversation with Nathan, he said the SoW essentially didn't have "deliverables".

We have 10 days of proserv time remaining.

His suggestion for the remaining time:
"...migrating an application into the landing zone or building a CICD pipeline so your developers can build a new application on the platform."
