### ISSUE TITLE
 Luke’s Transition

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder-technology-and-ux#173]
**Describe the issue**

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Gather all documents 
- Confirm we have confidential storage in Teams or set it up 
- Get full access for Shea (follow up with Teams team to explore access for Shea) 
- Guest mode not good enough 
- Get payment approval for Shea’s access 
- determine other required steps, put into backlog

**Comment by ActionAnalytics** [comment]
Helping Sid with the Scrum Ceremonies

**Comment by ActionAnalytics** [comment]
Provisioning Sid
