### ISSUE TITLE
Team Creation: Seek answers to team questions

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#174]
**Describe the issue**
The team has a few questions about the roles and org.  Surface team questions in standup or dedicated meeting to Peter & Gen.

**Which Sprint Priority is this issue related to?**
N/A

**Definition of done**
- Raise that team has questions during standup
- Word from above previously was that we would keep original positions.  Determine under new leadership does this continue? 
- Find answer to do we need Expense Authority? 
- What from our original positions carries over? 
- What’s our base positions now? 
- Flex days vs Holidays?

**Comment by lukegonis** [comment]
the could pathfinder team(s) need:
- some kind of admin support (AO14 Projct Admin?)
- project coding/budget
- purchase card

**Comment by glam-bert** [comment]
Hi folks, happy to talk about this at stand-up and/or sprint planning tomorrow.
