### ISSUE TITLE
Research requirements and expectations for Managed Cloud Services

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder-technology-and-ux#178]
Run workshop for Gen's team + demo for Pathfinder Team, incorporate input and schedule remaining workshops with ministry teams

Research ministry teams' requirements and expectations for Managed Cloud Services

DOD: For this sprint - as described, through to scheduling remaining workshops. 
(Overall: Complete 6 workshops, compile and analyse findings, report out.)

**Comment by ActionAnalytics** [comment]
Covered in new ticket
