### ISSUE TITLE
Terraform Cloud Meeting

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#182]
**Describe the issue**
We wish to fast track our configuration of Terraform so that we can connect it to GitHub in the optimal manner without causing security problems for the GitHub org.  We feel a meeting with Terraform will help us achieve this.

**Which Sprint Priority is this issue related to?**
Milestone #2

**Additional context**
Andy has offered to book the meeting

**Definition of done**
- A clear understanding of how to best connect GitHub to Terraform such that GitHub can trigger automation
- Solving of the IBM GitHub action problem with the provider archive to large to work in TF Cloud
- Understanding of how to connect Terraform to GitHub BC Gov org repos so that TF Cloud modules can include code from our GitHub repos without giving full org access
- Understanding of how to connect Terraform to GitHub BC Gov org repos so that TF Cloud can detect updates to code without giving full org access

**Comment by ateppin** [comment]
Initial meeting booked for Tuesday June 23 as a regular bi-weekly meeting

**Comment by ActionAnalytics** [comment]
Meeting 1 happened, Hashicorp is going and looking into our questions for us.  Will have a second meeting where we attempt to meet the DOD

**Comment by ateppin** [comment]
Sam created a YouTube video (https://youtu.be/JyqwVsyfpes) covering how to set up &/or configure.

Updates based on Sam's video:

@Subda, Julian IIT:EX – in my GitHub settings I can only work with my own personal org.  Do you have the rights to make changes to the settings for “bcgov”?

@Sam Gabrail - Do you know if TF Cloud for Business will be exactly the same when it comes to private registered modules?  And is TF Enterprise the same?  I realize TF Enterprise is on prem, but expecting that the VCS connection process to be similar.

Three options for modules then:
1.	Private modules & we have to connect the GitHub org
2.	Public modules & we can connect GitHub repo level (I’m assuming we’d make a repo just for modules & connect just that single repo)
3.	We get a new GitHub Org created specifically for TF modules & connect to that GitHub org

@Subda, Julian IIT:EX – what’s the likelihood of getting another GitHub Org created for TF modules?

**Comment by ateppin** [comment]
Julian followed up with Sam letting him know that the GitHub settings are different for "the larger org" than as personal org (which is what Sam covered in his video)

There were also some errors when trying to follow other steps.  Sam has suggested to try removing TF Cloud? from Github & re-doing.

**Comment by ActionAnalytics** [comment]
Still ongoing

**Comment by ActionAnalytics** [comment]
Blocked by 183
