### ISSUE TITLE
Terraform Cloud AWS Demo App Full Modularization

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#184]
**Describe the issue**
We wish to modularize as much as possible of the AWS TF code such that anyone trying to set up infrastructure for a deployment of the demo app can do so without having to deal with complex Terraform code.

**Which Sprint Priority is this issue related to?**
Milestone #2

**Additional context**

**Definition of done**
- Take the example in ticket #183 and apply it fully to as many dependencies as possible in the App infrastructure code (most likely the container cluster ECS, the load balancer, network, security, logs, possibly more)

**Comment by sid-gov** [comment]
Duplicate.
