### ISSUE TITLE
Adapt sample app AWS provisioning so it is repeatable and reliable

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder-technology-and-ux#190]
**Describe the issue**
Currently, there are some steps in the sample demo provisioning that do not work consistently, depending on the current state of the target account.  We need to adapt our steps so that they function reliably regardless of the current state of the account.

We are also missing a simple "cleanup" step.

**Which Sprint Priority is this issue related to?**

Demo enhancement.

**Additional context**

The specific resources that have been problematic are "service linked roles" and log resources (log groups and log streams).

**Definition of done**

The provisioning and deprovisioing steps can be run repeatedly and be relied upon to succeed.

**Comment by ActionAnalytics** [comment]
The logging groups work that already happened will help solve a lot of this

**Comment by sid-gov** [comment]
Closed.
