### ISSUE TITLE
Review/restore GitHub/ZenHub access for team members

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder-technology-and-ux#199]
**Describe the issue**
It appears that some access to GitHub as well as ZenHub may no longer be configured properly and those requiring access may not have the access they need.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**

We have had some team member changes, so we need reflect this, as well as ensure that others have not had their access inadvertently changed due to "housekeeping"/maintenance activities. 

**Definition of done**
- All team members have access to read/write repo issues in GitHub and ZenHub.  
- Also, all membership in the "Cloud Pathfinder Team" in GitHub accurately reflects our "real world" team membership.
- A process needs to be in place for when we onboard offboard (new team members joining soon)

**Comment by ActionAnalytics** [comment]
Might be related to work Shelly did, she may have context
