### ISSUE TITLE
Identify cloud compute + storage services for inclusion in Pathfinder

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder-technology-and-ux#2]
Working with business units with acute deployment issues as a guide to what needs are to be met.

RTB - Ritch McKlay
CAS - Moral or Alec

once we have a good idea of needs we can look at the best target for the workload

**Comment by sheaphillips** [comment]
There is probably a separate ongoing task to establish an maintain a prioritized funnel of services to light up.  I've changed to title to include "Pathfinder" to reflect the immediate tactical set of services driven by specific business areas who are already engaged vs. those that will be available within the MVP timeline.

**Comment by mumit** [comment]
My opinions on compute/storage for lighting up earlier than later:

- Compute: OpenShift platform on Azure
- Storage: Azure Filestore and Blob (I'm explicitly not including Managed Disk as that is basically the "I'll get myself a VM and a disk and ..." way). RTB seems to need Blob, unless they are looking for a specialized streaming service which is a different beast.

**Comment by kelpisland** [comment]
I agree with both of you.

I'll set up a new ticket for funnel creation / CRM kind of thing.

Also, let's assume 
1 - compute is covered for now with OCP 4.x in the gov Azure space.
2 - storage classes can be added to OCP or Min.io pod deployment as easy win.
3 - Alec W. from cas has volunteered to explore creation of Operator for storage provisioning if needed

**Comment by kelpisland** [comment]
March 16 meeting set up with Ritch.

CAS: Alec and Maral are fine tuning ask and are 100% on board.

**Comment by kelpisland** [comment]
CAS requests object storage in GCP Montreal 
- 1TB quota (estimated) to house batch data dumps from Environment and Climate Change Canada to BC Climate Action Secretariat (historically bi-weekly, CR in progress to nightly)
- No PII in the data set (potentially business sensitive information only, per signed PIA#ENV19025/ENV26-2019)
- Zip file exports from the Single Window Reporting System (SWRS) containing xml data dumps plus attachments uploaded by citizens to SWRS (no filetype filter imposed by Canada)
- Standard Storage Class in GCP, retention managed by application code (no retention policy in cloud)
- Uniform bucket-level access (each service environment is isolated and cannot access another environment’s resources, but share the same bucket namespace)
- Bucket provisioning by restful application (api abstracting the cloud service)
- Bucket “environment” set provisioned per service: dev, test, prod, tools
- Bucket “service” names to match OCP namespace prefix: eg “wksv3k” service for “wksv3k-dev”, “wksv3k-test”, “wksv3k-prod”, “wksv3k-tools” namespaces
- Bucket “namespacing” by convention eg. “${service}.${environment}.gcp.gov.bc.ca”
