### ISSUE TITLE
CAS usage questions regarding security and data classification

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder-technology-and-ux#210]
Describe the issue
- CAS, within NRM has onboarded services into GCP.
- Looking to get a sense of the landscape if there are areas of concern for privacy and security.

What is the value add to product/MVP?
- Security and the responsibility to citizen's data doesn't change if the data is in the cloud or not.

Which Sprint Priority is this issue related to?
sprint 8

Additional context
n/a

Definition of Done:
- Understand the current compliance of the usage? (current state)
- Understand the goal of compliance of the usage? (future state)
- What risk assessments have been completed?
- What is the data classification? (PI/Confidential/Public/Etc)
- What security controls/ security contracts are in place?

**Comment by ActionAnalytics** [comment]
GCP is currently unguardrailled

**Comment by ActionAnalytics** [comment]
No PI, aggregate data relating to carbon emissions, archiving data in google cloud storage due size reasons.

Archiving use case for objects.

Maral is the PO and likely has the PIAs

**Comment by ActionAnalytics** [comment]
Can start by asking ENV MISO?

**Comment by bluemel-gov** [comment]
- Reached out to NRM Security team for more information
- Waiting to hear back.

**Comment by bluemel-gov** [comment]
- Heard back from NRM Security
- Reviewing information for next steps.

**Comment by bluemel-gov** [comment]
- Spoke with my Director regarding contracts with Google. 
-- He will follow up with NRM Security team for what is in place

- Will re-open if issue not resolved.
