### ISSUE TITLE
Add LZ portability info to existing GC Cloud Brokering Service model

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder-technology-and-ux#211]
**Describe the issue**
Determine whether we can port existing LZ to a brokered GC LZ so that we can clarify details of GC Cloud Brokering Service customer journey (collaborate with Jenny)

**Which Sprint Priority is this issue related to?**
Develop alpha version of Managed Cloud Services Blueprint

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- We have a well defined process to get from our current AWS Landing Zone to GC brokered version of same
- most likely a one-pager
- may include a diagram

**Comment by sid-gov** [comment]
Quick touch-point with tech person involved in GC Brokerage.

**Comment by scayzer** [comment]
Discussed this briefly with Ryan Jaeger (AWS) on Monday (July 27), and have asked him for a couple of bullets on what would need to be done - it sounded very straightforward.
