### ISSUE TITLE
Refactor Demo App code for TF Modules

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#212]
**Describe the issue**
Have app consume simpler TF parts in order to make better experience for developer teams and reduce risk of teams making errors

**Which Sprint Priority is this issue related to?**
Cloud Platform

**Additional context**
- Will not include TF Cloud work

**Definition of done**
- Simplified code checked in
- Tested deployed to AWS
- Documentation DevHub

**Comment by ActionAnalytics** [comment]
@sheaphillips  to break into smaller tickets pls

**Comment by sid-gov** [comment]
Duplicate.
