### ISSUE TITLE
AWS Provider mapping to security schedule

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder-technology-and-ux#213]
**Describe the issue**

The Cloud Security Schedule (CSS) was an evolutionary outcome of a brick and mortar schedule and may have some gaps with respect Cloud Service Providers.  There is a desire to improve the CSS.  A CSP when signing up must comply with either BC standards or equivalent GC Protected B Medium Medium (PBMM), Fedramp, CSA*, Schedule G.  

Understand the current compliance against cloud security schedule against AWS.  AWS has existing reports, SOC 2 being one of them that may contain helpful security rankings we can map against.

**Value to the product/MVP?**
It would help with onboarding further services to cloud services, including MVP, and any early adoptors.

**Which Sprint Priority is this issue related to?**

**Additional context**

How to get to the SOC2 report in AWS:

Log in via KeyCloak and select the 'Province of British Columbia' AWS account, then master_readonly role
Click 'Log In To Console'
Using the 'Find Services' search box, type "Artifact"
Click 'View Reports'
Type "Service Organization Controls (SOC) 2 Report - Current" in the filter (or just type "SOC" and scroll down to find that report)
Compare the fields in the SOC 2 report to the CSS fields

**Definition of Done:**
- Review AWS SOC 2 for equivalencies and map to CSS
- A mapping that shows the security schedule vs the AWS security in a format that will inform further review of the CSS
- Excel document to be initially created in Teams, then ideally published on [GitHub in markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables)

**Comment by bluemel-gov** [comment]
- Created draft of equivalency services to match against cloud security schedule.

**Comment by bluemel-gov** [comment]
- met with James & Ryan on 7/13
- Was provided documents
- Aiming for completion by 30th or sooner.

**Comment by sid-gov** [comment]
PO closed this as it's broken down into smaller tickets. See linked tickets.

**Comment by ActionAnalytics** [comment]
Ticket 260 looks like a duplicate but 260 contains actionable steps on how to accomplish this.  Have a look at both and if in fact this is a duplicate, consolidate and close the extra one please.

**Comment by ActionAnalytics** [comment]
text from original ticket saved here in comments:
- Does CSS policy need to be changed to adapt to the CSP environment? Later work in further tickets based on this initial scan but not in scope

**Comment by bluemel-gov** [comment]
@sheaphillips Able to add me to any groups for access to AWS soc2 reports.  Getting this screen on attempted log in with idir
![image.png](https://images.zenhubusercontent.com/5e5eabb5c9cab6b5cca3163c/52db152c-a6b8-4c78-8ffc-e60364bc43a2)

**Comment by bluemel-gov** [comment]
- breaking up access and review to SOC2 report into a separate ticket, as it's blocked/waiting

**Comment by bluemel-gov** [comment]
broke request up into #260 too. As scope was too big

**Comment by bluemel-gov** [comment]
- found more controls against for the ' mapping that shows the security schedule vs the AWS security in a format that will inform further review of the CSS'. Have rough draft, aiming for next day or two

**Comment by bluemel-gov** [comment]
- Some branch work came in that delayed the progress on this. Planned to meet with Ryan J. on Thursday.
