### ISSUE TITLE
Create Toolkit Map with versions of Service Definition

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#218]
**Describe the issue**
We want one of these ties into our Service Definitions at each step of the way.
![Screen Shot 2020-07-03 at 11.55.38 AM.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/00595c33-22cd-4def-bd81-8ad43ce67c58)

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Talk to Julian for the source deck.  Work originated with Platform Team

**Definition of done**
- A diagram like the above example for peer review
(split into a different ticket - A tile in DevHub)

**Comment by ateppin** [comment]
Draft of the toolkit roadmap posted to Teams site for feedback
![image.png](https://images.zenhubusercontent.com/5e54089e72601cba366b5118/33ed2299-5688-4962-8887-fa96f5a607ea)
