### ISSUE TITLE
AWS SOAR/STRA

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder-technology-and-ux#224]
SOC2 and CSS cloud security schedule work will feed into this. 
Research AWS Online Docs - for Compute and Storage SOAR
Describe the issue
Research AWS online docs to input relevant content into SOAR/STRA

**Which Sprint Priority is this issue related to?**

**Value to the product/MVP?**
- Allow for adoption of services and recommended secure configurations

**Definition of done**
- Complete first round of research into SOAR questions for AWS.
- includes protected B data
- Scoped at the platform level
- draft ready for review (teams)

**Comment by ActionAnalytics** [comment]
Requires better DoD before it can be worked on

**Comment by bluemel-gov** [comment]
- Companion work in ticket #213 would feed into this.

**Comment by bluemel-gov** [comment]
- met with PO on 23rd to show document

**Comment by bluemel-gov** [comment]
- First draft complete.

**Comment by bluemel-gov** [comment]
- close as complete
