### ISSUE TITLE
Review of Vault ( Identity and password) tool from security perspective with ISB's ADMS

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder-technology-and-ux#241]
**Describe the issue**

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by sid-gov** [comment]
Closed as Vault is not part of our solution stack at this point. If we want to use vault in the future, our intent would be to use Platform Services shared instance. Nick will have security review done for vault.
