### ISSUE TITLE
Service Blueprint - front end activities

### ISSUE THREAD

**Issue by ateppin** [bcgov/cloud-pathfinder-technology-and-ux#242]
**Describe the issue**
Cloud Pathfinder, OCIO and Ministries need to understand, and be able to address user expectations and requirements for managed cloud services. Ministries need to understand their share of responsibilities for compliant use of cloud services. Our stakeholders will benefit from knowing what to ask from us.

We will start with creating the front end activities, up to the point of handing access keys to ministry teams

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional Context**
- centres on the customer journey
- the customer is the Early Adopter, in this case the customer is the service owner organization
- 2 customers? retail(developer teams) vs wholesale (IMB)
- front stage focuses on touch points between the customer and our service
- backstage is what is needed behind the scenes to make the above possible

**Definition of done**
- Clearly identify the customer(s) and the focus of this document
- Blueprint diagram updated with front end activities
- Peer reviewed

**Comment by ateppin** [comment]
After re-reading Gen's comments for the blueprint, changed the ticket to include both front & back stage, as she wanted the "front end section of the service" documented in the blueprint so we can onboard early adopters.

**Comment by scayzer** [comment]
Andy prepared, first draft. Reviewed with Paul (July 20) and incorporated his input. Have booked another review with Paul and Gen (July 22).

**Comment by ateppin** [comment]
Updating blueprint with feedback from first draft review with Gen & Paul.

main feedback - highlight the items that are mandatory for the EA journey.  Other tools/processes that are nice to have from a user testing point of view will only be used if they are in place in time.

**Comment by ateppin** [comment]
Updates sent to Paul, Stu & Gen

**Comment by scayzer** [comment]
Having incorporated input from review with Gen and Paul, have booked two further reviews for this week (July27-31) - will incorporate input and declare first iteration of Service Blueprint to be done.
