### ISSUE TITLE
Service Blueprint - First Draft review with stakeholders

### ISSUE THREAD

**Issue by ateppin** [bcgov/cloud-pathfinder-technology-and-ux#244]
Describe the issue
Cloud Pathfinder, OCIO and Ministries need to understand, and be able to address user expectations and requirements for managed cloud services. Ministries need to understand their share of responsibilities for compliant use of cloud services. Our stakeholders will benefit from knowing what to ask from us.

We will start with creating the front end activities (up to handing access keys to ministry team)
Which Sprint Priority is this issue related to?
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

Additional context
Add any other context, attachments or screenshots

Definition of done
- Meeting scheduled with stakeholders to review initial draft
- Feedback documented for next draft

**Comment by scayzer** [comment]
Reviewed with Paul, July 20. Updated draft Blueprint. Review with Paul and Gen booked for July 22.
