### ISSUE TITLE
SPIKE: Determine what components to include in the Service Blueprint

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#248]
**Describe the issue**
We wish to have a Service Design Blueprint that is a good fit for the needs of the MVP.  We may not need all the components available.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Clearly identify the customer (Ministry, MCIO, Digital Product Team, Developer Teams?) and is there a need for more than one track in the customer journey?  Identify the Customer vs Stakeholder.  Product team is first class citizen historically from the Pathfinder.
- Identify the components for a minimum viable product
- The document is in Miro and is editable (keep any PI or secrets out of this, intent is to publish this info into public - but only use the website, never the installed desktop app)
- A link from Teams is present and it is easy for others team members to find
- A document outlining how and when other components will be added in a maturity model
- Defining in the above document the recurring nature and frequency of this being a living document that will be reviewed.
- Set team calendar invites for the next review sessions (quarterly? 6 month?)

**Comment by ateppin** [comment]
Link added to Teams channel - ![image.png](https://images.zenhubusercontent.com/5e54089e72601cba366b5118/5ab16e3c-b7e8-4368-9d6f-8416095c9dd6)

**Comment by ateppin** [comment]
Met with Stu this morning to review some DOD items.

Meeting with Paul this afternoon to review our assumptions, answers & direction.

![image.png](https://images.zenhubusercontent.com/5e54089e72601cba366b5118/95efd6e5-3755-4846-9dc0-bb29decc5751)
![image.png](https://images.zenhubusercontent.com/5e54089e72601cba366b5118/bc87032d-4ba4-4538-9ee1-1aee142d4cdd)

**Comment by ateppin** [comment]
as per feedback from July 22 first draft meeting with Gen & Paul

develop a draft Service Blueprint right up to the point of handing access keys, and the Terraform scripts that we’ve run, to Early Adopter teams, who can then get working on the provisioned cloud infrastructure. Is this what Gen intended? Yes – confirmed with confidence!

Maturity of the blueprint will evolve as we discover & analyse more details from UX workshops, survey & actual feedback from early adopters.

More tools/processes and artefacts will be added to the roadmap during this evolution.
