### ISSUE TITLE
Map existing SOC2 Report to CSS

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#260]
**Describe the issue**
AWS has a pre-made SOC2 report that could cover some of the areas of focus of the Cloud Security Schedule.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
How to get to the SOC2 report in AWS:
- Log in via KeyCloak and select the 'Province of British Columbia' AWS account, then master_readonly role
- Click 'Log In To Console'
- Using the 'Find Services' search box, type "Artifact"
- Click 'View Reports'
- Type "Service Organization Controls (SOC) 2 Report - Current" in the filter (or just type "SOC" and scroll down to find that report)
- Compare the fields in the SOC 2 report to the CSS fields

**Definition of done**
- An Excel sheet stored in Teams containing the mapping of AWS SOC 2 to BC Gov CSS is completed and available for others to view

**Comment by ActionAnalytics** [comment]
Closed duplicate with 213

**Comment by bluemel-gov** [comment]
- Re-opened as #213 was too big of a task

**Comment by bluemel-gov** [comment]
- Not started yet due to work on #213

**Comment by bluemel-gov** [comment]
- Covered in alternate controls
