### ISSUE TITLE
Get signoff for AWS to CSS mapping

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#261]
**Describe the issue**
The signoff is necessary because it will be part of allowing for PI production workloads in AWS.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
See ticket 213

**Definition of done**
- Mapping deliverable from ticket 213 reviewed / signed off ISB Management
- Mapping deliverable from ticket 213 reviewed / signed off Gary Perkins

**Comment by bluemel-gov** [comment]
- Not started since 213 work is ongoing
