### ISSUE TITLE
Observe an existing Community of Practice

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#263]
**Describe the issue**
Executive at BC Gov has frequently described communities of practice as being the highest value item of interest for them per a survey of ministry execs.  The service design work include space for Communities of Practice and there is an opportunity to observe a community of practice on Aug 5. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
https://www.meetup.com/DevOps-Commons/events/272132515/

**Definition of done**
- A list of observed characteristics of a long lasting BC Gov Community of Practice
- Possibly survey results from a questionnaire that may be presented to the community

**Comment by scayzer** [comment]
Sat in on first half of DevOps Commons meeting. 45+ attending, highly engaged community of practice -  a good candidate for a CoP to UX test some CoP responsibilities in our Managed Cloud Services approach.
