### ISSUE TITLE
SPIKE: Research differences between GC and BC LZ auth mechanisms

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#282]
**Describe the issue**
AWS reports that based on preliminary review of the Gov of Canada (GC) Landing Zone (LZ), there are significant differences in the authentication mechanism.  BC Gov uses KeyCloak due to its multi-auth provider compatibility and its proven track record in BC Gov app development.  GC apparently depends on Active Directory for its auth.  In order to plan the work around a move to GC, we need to understand what the differences in authentication mean.

**Which Sprint Priority is this issue related to?**
Landing Zone Updates & Merging with GC

**Additional context**
- Requires access to GC LZ
- Requires access to GC LZ codebase

**Definition of done**
- Well defined tickets are created that describe any work that would have to happen for authentication to work the way we have it now in BC Gov AWS via KeyCloak

**Comment by ActionAnalytics** [comment]
Kind of need a GC repo or a live LZ in order to proceed

**Comment by sid-gov** [comment]
Decision made to pathfind with LZ2 so ticket is no longer needed. Closed.
