### ISSUE TITLE
Manage cloud workspace metadata as part of provisioning lifecycle

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder-technology-and-ux#288]
**Describe the issue**

Currently we do not have an explicit set of metadata attributes for cloud workspaces.  these are crucial for tracking/governance as well as for billing.  We need to identify the elements that we want to apply and provide a mechanism to apply and manage these as part of our provisioning automation process.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by sid-gov** [comment]
@ActionAnalytics - Julian, is this going to be worked on this sprint seeing that project provisioning automation is not part of sprint 11 milestones?
