### ISSUE TITLE
Investigate if we can auto-provision an instance of Dynamics365 (online)

### ISSUE THREAD

**Issue by mumit** [bcgov/cloud-pathfinder-technology-and-ux#29]
**Describe the issue**

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by sheaphillips** [comment]
Is this to see if there is an API to provision Dynamics?

**Comment by kelpisland** [comment]
yes - I found this link that seems like it's possible but needs to interface with O365 tenancy.

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/online-management-api/get-started-online-management-api#service-url

**Comment by sheaphillips** [comment]
there are approximately one bazillion options for Dynamics 365, each with their own pricing, access parameters, etc. so it will be interesting to explore what's possible and of value based on users' needs.

**Comment by sheaphillips** [comment]
@ateppin what / how have you provisioned Dynamics 365 so far for ministry clients?  Is this a click your way through a wizard thingy, or...?

**Comment by ateppin** [comment]
@kelpisland - the link you found requires a rather high level role (global) but perhaps a service level (Dynamics admin level) might work.

**Comment by ateppin** [comment]
@sheaphillips - there are a bazillion & one ;)

Initially (couple of years ago) - before my time) - OCIO had purchased the "Customer Engagement" _bundle_ for Dynamics online.  This included Sales, Customer Service, Field Service & Project Service Automation.  Since this time MSFT have changed the way they offer Dynamics online.

**Comment by ateppin** [comment]
@sheaphillips - the current process for ordering/provisioning today:

1. Consulting order via iStore to CSAM (Teresa Hall-Patch)
2. Teresa discusses options with client & determines licensing requirements for the multi-year commit
3. Client orders/creates IDIR security group & requests sync with AAD
4. Client submits details for URL, security group & options to Teresa
5. Teresa sets up/assigns licensing etc
6. Request comes to me to manually create the instance with the options listed in #4
7. Configure instance for roles & add client "sys admin" & hand over the keys to the client

**Comment by ateppin** [comment]
Found the following links over the weekend for further investigation Monday/Tuesday

https://admin.services.crm3.dynamics.com/api/v1.2/instances

https://docs.microsoft.com/en-us/rest/api/admin.services.crm.dynamics.com/instances/provisioninstance
will this provision a dynamics instance?  or what does it provision

https://docs.microsoft.com/en-us/rest/dynamics365/customer-engagement/index

https://www.youtube.com/watch?v=yA9vHb5AuV0

https://admin.services.crm.dynamics.com/swagger/ui/index - although this has been deprecated

https://community.dynamics.com/crm/b/nishantranaweblog/posts/sample-code-to-delete-instance-using-online-management-api-in-dynamics-365-customer-engagement
