### ISSUE TITLE
Corporate managed cloud services UX Workshop - HEALTH

### ISSUE THREAD

**Issue by ateppin** [bcgov/cloud-pathfinder-technology-and-ux#296]
**Describe the issue**
We have ideas from the 2019 Service Design workshops re what sort of user experience ministry teams will require when they access cloud services - we need to test assumptions and gather more information to inform our design of the service.

**Which Sprint Priority is this issue related to?**
Alpha version of our Managed Cloud Services Blueprint

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Assist facilitate session
Capture client inputs
UX workshop conducted, and findings so far compiled on ConceptBoard.

**Comment by scayzer** [comment]
Workshop completed: August 26, 2020.
