### ISSUE TITLE
Provision resources for Registries team, per email request

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder-technology-and-ux#300]
**Describe the issue**
The registries team has requested some new operations related resources (Tools, Dev, Test, Prod) alongside those they already have.  @sheaphillips and @ActionAnalytics see email from their technical lead.  

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- The Registries team has been given a project registries-style form to complete

**Definition of done**
- Registries team is able to access and self-provision within their workspaces

**Comment by glam-bert** [comment]
Where is this workspace?
