### ISSUE TITLE
Determine target sites for publication of each of our key artifacts (GitHub, DevHub, Digital.gov.bc.ca ..)

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder-technology-and-ux#303]
**Describe the issue**
We already have several artifacts ready for publication, and there will be more completed at an accelerating pace over the next few weeks. It will greatly enhance our engagement of stakeholders (also accelerating), if we can direct them to our relevant documentation, diagrams, wizards .. etc. Also consider Documize. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Some artifacts will be private. Most will be public. 

**Definition of done**
- Figure lightweight high-level classification scheme for the artifacts (what do we need to keep secret? e.g: secure network diagrams, landing zones etc.)
- Determine the different kinds of publication, collaboration and artifact storage our team does and outline them in a spreadsheet;

**Comment by glam-bert** [comment]
Recommend consulting with Heather Remacle and Justin Hewitt to get their recommendations on where artifacts should live.

**Comment by ateppin** [comment]
@glam-bert   - Will do, thanks.

**Comment by ateppin** [comment]
Teams channel created "CP Internal" for core CP team

**Comment by ateppin** [comment]
Emailed Heather & Justin per Gen's suggestion

**Comment by ateppin** [comment]
Response from Heather:

I have no great answer for this… my team discusses it as part of our working agreement, and we adjust as our experience and outputs need us to…

We generally work in the open and have refined our scope of tools to Github/zenhub and Miro for that. 

Our team has a private MS teams channel in the Exchange Lab team, where we keep files that are transitory (not really useful for our community).

Anything truly sensitive ends up on the LAN. 

That being said, if your team were to come up proposed classifications for a variety of tools, that would be rad.

**Comment by ateppin** [comment]
We also know we need an alternative to Miro for security reasons & Ryan/ISB have pulled together some details based on a request we made for them to review Lucidchart, Terrastruct & Concept Board.

**Comment by ateppin** [comment]
Uploaded a spreadsheet to Teams with a possible matrix to start the conversation with the CP team about where artifacts should be published.

https://teams.microsoft.com/l/file/3B6EDB39-26B2-4840-972E-4DBF73D333C1?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=xlsx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368-CPInternal%2FShared%20Documents%2FCP%20Internal%2FReference%2FArtifact%20Locations.xlsb.xlsx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368-CPInternal&serviceName=teams&threadId=19:037a2a9775234a2f82886646fa8b22de@thread.tacv2&groupId=293d2a85-5978-44d6-a2c8-b0d3c5f7e1af

**Comment by ateppin** [comment]
Worked through feedback from Stu & tweaked the spreadsheet.

Met with Julian & his feedback included adding Documize back to the mix as well as G Suite as this is/was being used by a couple of team members

I have contacted Luke to determine who is controlling our instance of Documize & to get that passed to Julian.

**Comment by ateppin** [comment]
Updated spreadsheet & notified Stu & Julian.

Still waiting to hear back from Luke about Documize.

**Comment by ateppin** [comment]
Luke responded granting Julian full control to the cloud pathfinder location on documize

**Comment by ateppin** [comment]
[Spreadsheet ](https://teams.microsoft.com/l/file/3B6EDB39-26B2-4840-972E-4DBF73D333C1?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=xlsx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368-CPInternal%2FShared%20Documents%2FCP%20Internal%2FReference%2FArtifact%20Locations.xlsb.xlsx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368-CPInternal&serviceName=teams&threadId=19:037a2a9775234a2f82886646fa8b22de@thread.tacv2&groupId=293d2a85-5978-44d6-a2c8-b0d3c5f7e1af)on Teams Internal has been updated
