### ISSUE TITLE
SPIKE: How will EA program help CP?

### ISSUE THREAD

**Issue by ateppin** [bcgov/cloud-pathfinder-technology-and-ux#305]
**Describe the issue**
We need to understand & be able to capture/measure how the Early Adopter program will benefit the Cloud Pathfinder mission. We want learnings and enrichments from the work with EAs. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Agreement on value for CP team 
- List of features, capabilities we expect EA teams to use (KPIs)
- Come up with question(s) we ask in their demos that focus them on delivering value back to us
- Review with Development leadership (Julian, Shea)

**Comment by glam-bert** [comment]
Recommend we do not narrow this to how this will inform development/technology but also how the EA program will inform the establishment of a sustainable operational service (including what human resources are needed to support this service).

**Comment by ateppin** [comment]
Started a document in the EA folder on the Teams site

https://teams.microsoft.com/l/file/A120AFF7-B17F-4BC8-8110-06A8828E2E95?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368%2FShared%20Documents%2FGeneral%2FEarly%20Adopter%20Program%2FHow%20will%20EA%20Program%20help%20CP%20mission.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368&serviceName=teams&threadId=19:79c414cbe8dc41f3b047a00bc455c318@thread.tacv2&groupId=293d2a85-5978-44d6-a2c8-b0d3c5f7e1af

**Comment by ateppin** [comment]
Sent a document link to Shea & Julian for their review/input.

**Comment by ateppin** [comment]
Met with Julian & Shea - Oct 15.

Comments compiled into the document & possibly the service blueprint
