### ISSUE TITLE
Confirm Market Segment for Service Blueprint Audiences

### ISSUE THREAD

**Issue by ateppin** [bcgov/cloud-pathfinder-technology-and-ux#306]
**Describe the issue**
The service blueprint is becoming a complicated diagram with a lot of information.  We are determining a better viewing option by breaking the diagram into stakeholder or market segments.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**

**Definition of done**
- market segments identified
- Potentially adaptable to the service blueprint
- Identify key concerns for each segment
- Peer review and input
- Approval of CP Leadership team (Gen, Paul, Julian)

**Comment by sid-gov** [comment]
Market segments (by priority): 
1. Client Ministry Executive Leadership team
2. Client Ministry Product teams 
3. Service delivery partners (ES, Platform Services, vendor partners)
4. OCIO Cloud team (team that is going to operationalize Managed Cloud Services)
