### ISSUE TITLE
Set an agenda and meet with the CRA team to learn what we can about their experience with the GC Cloud Brokering Service

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder-technology-and-ux#310]
**Describe the issue**
CRA has used the GC Cloud Brokering Service for some time now - they must have lessons learned and patterns for success that they could share with BC - particularly with respect to the use of the GC CRM system for processing Service Orders. We have many questions about how this will work for us.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Negotiate an agenda and schedule for a meeting with the CRA team;
Conduct the meeting and capture as much helpful information as possible - also ask if there is any other documentation they can share.

**Comment by ActionAnalytics** [comment]
Agenda set, delayed per CRA availability

**Comment by scayzer** [comment]
2020-10-08 - no longer needed per progress with SSC
