### ISSUE TITLE
SPIKE: Gap analysis of difference in account creation mechanisms between GC & BC Gov LZ

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-technology-and-ux#312]
**Describe the issue**
Account creation in BC Gov's Landing Zone (LZ) seems to be heavily event-driven whereas we suspect the GC account creation process is fairly rigid. We wish to understand the gaps so we can plan any work to have event-driven account creation in GC Cloud. 

**Which Sprint Priority is this issue related to?**

**Additional context**
- Language differences between BC (cloud formation and stacks) & GC LZ (CDK, which is either Typescript or Python that generates cloud formation)

**Definition of done**
- Word Document/PowerPoint in Teams outlining the differences between account creation
- Set of estimated tickets describing the work needed to fill the gaps

**Comment by ActionAnalytics** [comment]
Shea is covering this now
