### ISSUE TITLE
SPIKE: Gap analysis on security differences between GC & BC LZ

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-technology-and-ux#313]
**Describe the issue**
Security and Privacy have just reviewed the existing LZ1 and we wish to make sure that their review is still valid and if not create tickets to understand the differences between security implementation and monitoring in BC and GC Landing Zone. 

**Which Sprint Priority is this issue related to?**

**Additional context**

**Definition of done**
- Word/PowerPoint document in Teams that outlines the security differences 
- Creation of well-formed tickets describing the work that needs to be done to fill any gaps.

**Comment by ActionAnalytics** [comment]
Covered by Ryan, Shea and ISB
