### ISSUE TITLE
Review 'Bjorn' persona journey

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder-technology-and-ux#32]
Here is a link to Justin Hewitt's docs:
https://docs.pathfinder.gov.bc.ca/s/boj0qcchpp5rkld1o0u0/ocio-cloud-pathfinder/d/boj46o4hpp5rkld1o11g/cloud-pathfinder-docs?currentPageId=bpbcdqumgo8985hct1mg

**Comment by kelpisland** [comment]
@hromanow  - let me know when you are available to go through this material and we can make some sub tasks based on what we have.
@jromero2020  - do you have time tomorrow to join too?

**Comment by kelpisland** [comment]
I'll do a walk through as part of sprint review
