### ISSUE TITLE
Start a Early Adopter onboarding document

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-technology-and-ux#323]
**Describe the issue**
CP Team has some high-level onboarding information in the Service Blueprint. As part of the EA program, we wish to have a place to have a detailed final version of the onboarding checklist. The onboarding doc is intended to be both internal (CP team) and external document (EA Teams). 

**Which Sprint Priority is this issue related to?**

**Additional context**
See Service Blueprint

**Definition of done**
- Document is created in Teams with uniform format and table of contents
- Document peer-reviewed

**Comment by ateppin** [comment]
Table of Contents started for the onboarding document & saved to Teams site for peer review.
https://teams.microsoft.com/l/file/BFCAD393-2D92-4A8D-9F0B-22B793671FEA?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&fileType=docx&objectUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368%2FShared%20Documents%2FGeneral%2FEarly%20Adopter%20Program%2FEA%20Onboarding%20Requirements.docx&baseUrl=https%3A%2F%2Fbcgov.sharepoint.com%2Fteams%2F01368&serviceName=teams&threadId=19:79c414cbe8dc41f3b047a00bc455c318@thread.tacv2&groupId=293d2a85-5978-44d6-a2c8-b0d3c5f7e1af

**Comment by ateppin** [comment]
Contacted CP team via Teams chat to review the document
