### ISSUE TITLE
Review our environmental scan re procurement - Ontario, Alberta, New Brunswick

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder-technology-and-ux#325]
**Describe the issue**
Recent call with AWS Federal team discussed CSP procurements underway in Alberta, Ontario and New Brunswick.  

Need to verify that we know all that we need to know about these procurements - it may be very much to our advantage to follow the New Brunswick pattern.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Zach to share summary of whatever research has already been done on these procurements;
If there is more to explore, we can schedule meeting(s) as needed.

**Comment by ZachWoodward** [comment]
Do we have any details on these procurements? I have nothing at this time.

**Comment by sid-gov** [comment]
@paulroberts68 @scayzer I'm closing this ticket since this looks pretty old. Pls let me know if i'm wrong in assuming that.
