### ISSUE TITLE
Schedule and conduct follow-up meeting to develop Early Adopter Submission for IIT

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder-technology-and-ux#328]
**Describe the issue**
We've met with several early adopter candidates for initial discussion of our program and the project(s) they're planning to migrate to cloud. We've also developed a set of criteria that measure the risk (and, conversely, likelihood of success) for each project and team. Next step is to meet again with candidates and collaborate in rating their project and team against our criteria for success. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Schedule follow-up meeting with IIT team;
Complete an Early Adopter Submission for each project and team that they bring forward.

**Comment by scayzer** [comment]
Meeting with IIT scheduled for 2020-09-14 (further out as requested by IIT team)

**Comment by ActionAnalytics** [comment]
Mines is throwing their hat in the mix too via Jill, Aaron, Paul D.

**Comment by scayzer** [comment]
Meeting held with Julian, Gen, Shea, Andy (2020-10-20) - at this point we have Mines (MDS) as our strongest Early Adopter candidate, and several other options still in process.

Critical success factor here is to keep the conversations going, and avoid saying no to candidates, Instead it will be, let's keep working together towards onboarding in a subsequent phase of our EA Program.

**Comment by sid-gov** [comment]
Aside from Mines, they were a few other candidates that needed to be looked at. See Stu for more details.
