### ISSUE TITLE
SPIKE: Diagram the flow to security compliance

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#337]
**Describe the issue**
In order to create tickets and prioritize work, the team needs a clear shared understanding of what AWS MVP security compliance (what security artifacts need to be done for MVP) looks like and what documents and processes need to happen to arrive there.  

We also would find it valuable to see the Azure security compliance stream depicted in parallel.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**

**Definition of done**
- the drawing captures the dependencies of ticket 213
- a draw.io diagram representing what documents are in scope for security compliance and any processes that need to happen along the way,
- stored in either the teams security folder or the "diagrams with source files", such that
- future tickets can be well defined using this common understanding
- this simple diagram would be a "here you are on the journey" subway map kind of thing

**Comment by bluemel-gov** [comment]
@sid-gov @ActionAnalytics First snapshot dated with sept 21st suffix in 'diagram with Source Files'. For your review/edits/feedback/questions. Thanks
