### ISSUE TITLE
Get an Azure resource group for storage provisioning

### ISSUE THREAD

**Issue by mumit** [bcgov/cloud-pathfinder-technology-and-ux#34]
In order to test out the provisioning of Azure storage resources, we need a resource group in BC Gov Azure tenant.

This is a prerequisite to a number of tasks in coming sprints. For this current sprint, it's related to #4.

COS:
- We have a Azure resource group (RG) in non-production subscription
- We have the appropriate grants to be able to provision storage resources in the RG

**Comment by mumit** [comment]
- Jon McCaig is creating an RG for testing purposes
- Jon will assist in getting us started
- Next up is a call with Jon, Andy and Julian to see what the next steps are

**Comment by mumit** [comment]
Jon has created 'Testautomations01’ RG under the BCGov-MGD-CLNPD1 subscription. Next step is to try it out tomorrow.

**Comment by mumit** [comment]
@ateppin - if you are able to provision some blob and file storage, save the automation code (ARM or Powershell?), then we can close this issue.

**Comment by ateppin** [comment]
We stepped through creating a storage account (saved as a template) & also created a container for blob & a file share.

You saw that there was no option to save the blob & file share as a template.
