### ISSUE TITLE
SPIKE - Connect with ISB SecOps, ES and EA re AWS Network Architecture

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#341]
**Describe the issue**
We want to pull in and go over the proposed LZ2 style of network architecture with our partners from within BC Gov. We wish to line up with their schedules. Booked for 21st Oct

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- Chris Chen
- follow up with Cloud Directions group

**Definition of done**
- Find out from Julian, Stuart and Gen specifically who to reach out to
- Meet with them get time and work estimates, without sharing diagrams (that's next ticket)
- Create tickets that can go in sprint for collaborations

**Comment by sid-gov** [comment]
@glam-bert @ActionAnalytics - Did we have follow-up tickets coming out from this meeting? If not, can we close this?

**Comment by bluemel-gov** [comment]
- spoke with @ActionAnalytics 
- nothing immediate to action
- review of MVP done, no concerns
- Started ongoing discussion for collaborating ( IP ranges, SDN, etc)
- Closing as complete
