### ISSUE TITLE
Implement basic Geofencing in LZ2

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-technology-and-ux#343]
**Describe the issue**
We wish to lock out non-Canadian access to LZ2, exceptions could be made later on. 
Geofencing is partially the restriction of certain non-Canadian regions in AWS but also the denying of non-Canadian IPs ability of using the AWS console, CLI and possibly even web traffic (unlikely but nice to talk about)
This is for developer access to AWS developer tools and control panels, not workloads, although a working solution could in future offer a reusable pattern for teams wishing to do the same.

**Which Sprint Priority is this issue related to?**

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Working code asap in LZ1, in LZ2 by end of sprint.  This will require coordination with other developers as access is opened to LZ2.
- WIP artifacts to be kept in Teams
- Confirmation that LZ2 doesn't already have geofencing 
- A one-page document enhancing the diagram suitable for starting a discussion with our internal security partners prior to demo 
- A draw.io diagram suitable for demo deck/management that clearly illustrates how geofencing is applied
- Both draw.io source and rendered png to be saved to our 'diagrams with source files' in Teams
-  We will do a first pass via the console
- A manual how-to document what settings will change suitable to feed into automation

**Comment by ActionAnalytics** [comment]
- A solution that does similar entity tracking mapping example exists that Bahram is looking at in AWS.
- Some Identity Providers like Keycloak have the ability at the MFA check to check IP location. Could Keycloak check as well.
- Current lambda for the AWS custom page has a firewall (old separate branch by Ryan J available with example - Shea to look at) & WAF, locks down access to only from Keycloak, can add rules to restrict only to Keycloak, possibly Canada.

**Comment by cloudsmart** [comment]
See attached document for details
