### ISSUE TITLE
AWS FA review by Security

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-technology-and-ux#346]
**Describe the issue**
Security branch needs to review the documents sent by AWS Framework agreement (FA) including Annex-E. 

**Which Sprint Priority is this issue related to?**

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Annex-E has been reviewed by CP Security in the AWS Reading room and feedback provided to ISB

**Comment by bluemel-gov** [comment]
- awaiting updates from ISB management

**Comment by sid-gov** [comment]
Ready for review and sign-off.
