### ISSUE TITLE
Finalize concept case and get it through approvals

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#347]
**Describe the issue**
The concept case draft is done and needs to be reviewed before submission

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- The draft has been finalized for content and word count
- CP Executive has incorporated feedback and review

**Comment by sid-gov** [comment]
Same for this @glam-bert. :)
