### ISSUE TITLE
Finalize draft of Sid & Paul's GC procurement diagram

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#350]
**Describe the issue**
There was a diagram of a ministry team journey through GC

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- convert to draw.io
- save in teams
- update to reflect the market segment
- Review with Julian

**Comment by scayzer** [comment]
Started diagram in Draw.io (2020-11-04) and passed to Sid for completion

**Comment by sid-gov** [comment]
Diagram saved in Teams and reviewed by PO. Closing as complete.
