### ISSUE TITLE
Develop a template for capturing the procurement selection criteria for cloud services that ministry teams decide to use

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder-technology-and-ux#357]
**Describe the issue**
This is a templated word document form that each Team that has passed the EA vetting process will fill out as a 2nd step and become part of a record. Access to the Government of Canada Cloud Brokering Service will give us access to cloud services (compute & storage) from the different Cloud Service Providers (CSP). Our BC government Managed Cloud Service will provide corporate PIA and STRA for a selection of services from each CSP, and these will then be available to ministry teams

Early Adopter (and future) ministry teams will select cloud service providers (CSPs) that best meet their needs, and will need to justify their selection per Core Policy, Chapter 6 (Procurement) - why use AWS services rather than Google, or Microsoft or ..   This demonstrates that the team has evaluated cloud service providers in a procurement compliant manner, justifying perhaps by a specific service they want (like S3 in a particular CSP)

The selection criteria captured will become a government record.

**Which Sprint Priority is this issue related to?**
Sprint 12

**Additional context**
We need to understand the current procurement processes and technical gaps. 
We don't need to do a service order every time a team wants a change.

**Definition of done**
- Understand current procurement processes from Zach and peer-review;
- Prepare an initial template (which includes sample text) for selection of cloud, storage and container management services;
- Selection criteria captured will become a government record of the procurement process;
- Review with Gen, Paul, Julian, Zach and incorporate their input.
- Create tickets for next steps after review.

**Comment by sid-gov** [comment]
@ActionAnalytics - Edited the ticket. Can you pls review this ticket before putting it in the sprint backlog?

**Comment by ActionAnalytics** [comment]
@sid-gov not sure I understand what this deliverable will look like.  Could you flesh out the DoD to include a description of what form this template is intended to take?  Is this a document that lives somewhere, is this a form in a requests system at GoC or platform services?  What is this?

**Comment by scayzer** [comment]
Reviewed by Gen, Paul and Julian, then final review and fine-tuning with Paul 2020-11-06
