### ISSUE TITLE
Configure KeyCloak as external SAML Identity Provider in AWS

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#367]
**Describe the issue**
We need to enable IDIR as a means to authenticate to AWS while leveraging all the role based and logging that comes with the Landing Zone codebase.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Config objects are created in AWS

**Comment by sheaphillips** [comment]
As of today, this is mostly done.  Outsanding step is to create role and trust relationship.
