### ISSUE TITLE
Create a new KeyCloak realm for AWS LZ2

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#369]
**Describe the issue**
AWS Landing Zone 2 needs a KeyCloak realm because the client ID must be unique within a realm and have a particular set value (meaning we can't have both LZ1 and LZ2 in the same realm)

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- New KeyCloak realm is set up
- Julian has access

**Comment by sheaphillips** [comment]
@sheaphillips follow up with Platform Services team on status.
