### ISSUE TITLE
Meet with AWS to review Shared Responsibility model

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder-technology-and-ux#373]
**Describe the issue**
AWS Shared responsibility confirmation over our model for shared responsibility

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- Need more info to define this ticket (PO to enquire)

**Definition of done**
- Meeting with AWS has happened
- Any feedback is gathered, Action items handled

**Comment by sheaphillips** [comment]
@ActionAnalytics I've removed myself as an assignee on this one as I'm unclear on how to move it forward.  @ActionAnalytics please poke me if/when you need a hand with this or want to discuss.

**Comment by ActionAnalytics** [comment]
Met with Ryan from AWS, went over model in detail, no changes requested
