### ISSUE TITLE
Ensure Security review for AWS FA (Annex E) is approved and signed

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-technology-and-ux#382]
**Describe the issue**
We want to make sure that this gets completed so we are assigning CP Security to guide this through the process to completion. 

**Which Sprint Priority is this issue related to?**

**Additional context**
Security Review is currently done and in ISB's inbox for approval. 

**Definition of done**
- Written confirmation of approval provided
- Follow-up on Oct 14th 
- Identify and bring forward any blockers to CP Leadership

**Comment by bluemel-gov** [comment]
- Being addressed by ISB management
