### ISSUE TITLE
 Account/Resource Provisioning Architecture

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder-technology-and-ux#4]
Work is currently roadmapped for the Next Generation Security Project for a scalable method of managing admin and provisioning accounts across multiple tools, platforms and providers.

This architecture create the picture for the collaboration with the next gen. sec team on that initiative. 

Working assumptions:
Github id and active directory as MVP identity providers
Verified credentials a distributed trust multi factor
key cloak as authentication/authorization manager
DevHub as discoverability/ front door

**Comment by kelpisland** [comment]
A working prototype has been completed by @ShellyXueHan and @esune using Hyper-ledger Aires and Key Cloak to provide a verified credential for Key Cloak admin access. Details to follow.

**Comment by kelpisland** [comment]
Here is a functional overview:
https://docs.pathfinder.gov.bc.ca/s/boj0qcchpp5rkld1o0u0/ocio-cloud-pathfinder/d/bokbujkhpp5rkld1o2j0/cloud-compute-and-storage-docs?currentPageId=bpg37bb0acqjm3hnvc60

Each of these will need to be broken out into discrete tasks.
