### ISSUE TITLE
Payment method for Mural Required

### ISSUE THREAD

**Issue by ateppin** [bcgov/cloud-pathfinder-technology-and-ux#402]
**Describe the issue**
We were using a trial version of Mural (after moving from Miro & Draw.io) & that trial is expiring on Oct 25.
We will need a credit card to pay for the 2 member licenses

Work with Sid to secure the credit card

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Credit card in place for Mural

**Comment by sid-gov** [comment]
Approval request sent to Meara for processing.

**Comment by sid-gov** [comment]
Mural upgrade complete with p-card details in place.
