### ISSUE TITLE
Deploy sample app to LZ2

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder-technology-and-ux#418]
**Describe the issue**
The sample app is our canary test that proves that we are ready to deploy apps to LZ2. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

- AWS  technical expert has done some initial work to make the sample app deployable in an SEA-based LZ: https://github.com/rjjaegeraws/startup-sample-project/tree/aws-sea

**Definition of done**
- Sample app needs to be up and running in LZ2 PBMM (Protected B Medium/Medium) compliant space in Dev OU (Organizational Unit).

**Comment by ActionAnalytics** [comment]
FYI Ryan Jaeger has already done this and has code completed.  Please reach out to him.

Also coordinate with Warren as he is working on the local dev aspect of the app.
