### ISSUE TITLE
Link LZ2 into GoC brokerage system

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder-technology-and-ux#422]
**Describe the issue**
Currently, our LZ is not "linked" into the GoC brokerage.  This needs to be in place for billing and other business purposes.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Our existing LZ is confirmed to be connected with GoC.

**Comment by sid-gov** [comment]
Nothing to do here. Covered by @scayzer
