### ISSUE TITLE
Manually create a routing so that Demo app can be viewed from the outside world

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder-technology-and-ux#435]
**Describe the issue**
This is important because our EA teams need to be live and reachable from the internet. We need to understand how to do this using the structure of LZ2. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- There is a markdown file describing the required steps in the SEA GitHub repo.
- consultation with AWS technical expert

**Definition of done**
- Procedure documented in LZ Ops repo and 
- demo app reachable from the outside world
- *clarification*  should include DNS config to allow access via a URL
- *clarification* should include configuration of TLS for internal traffic path from perimeter network to app ALB

**Comment by sheaphillips** [comment]
Included this in Sprint 15 as it is closely tied the dpeendent ticket and it doesn't make much sense to do that one without this one.

**Comment by wrnu** [comment]
The documentation for exposing a public facing workload are available here: https://github.com/aws-samples/aws-secure-environment-accelerator/blob/master/docs/installation/guides/public-facing-workload-via-fortigate.md

**Comment by wrnu** [comment]
[PR#1](https://github.com/BCDevOps/cloudops/pull/1) documents the steps in the [CloudOps repo](https://github.com/BCDevOps/cloudops)

Internal TLS is handled by the defualt self-signed certificated that is added to the internal ALB using [terraform](https://github.com/bcgov/startup-sample-project/blob/master/terraform/aws/alb.tf)
