### ISSUE TITLE
Azure Guardrails

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder-technology-and-ux#51]
Describe the issue
- Provide a document that highlights the best practices of MSFT against government requirements for adoption at OCIO or Ministry level

What is the value add to product/MVP?
-Security and the responsibility to citizen's data doesn't change if the data is in the cloud or not.
-Repeatable questions and answers that can be used by ministries to ensure security practices are in place.

Which Sprint Priority is this issue related to?
-sprint 8

Additional context
n/a

Definition of Done:
- Document showing comparison of items in cloud security schedule against one or more services in AWS and how they meet or not.
- Reviewed by one (or more) member of CP
- Reviewed by ISB management
- Submitted for approval to ISB management

**Comment by bluemel-gov** [comment]
- Reviewed Azure controls against Cloud security schedule

**Comment by bluemel-gov** [comment]
- Some edits/changes to make

**Comment by bluemel-gov** [comment]
- Reviewed with ISB, minor edits to make

**Comment by sid-gov** [comment]
PO says this is scoped out as it doesn't relate to MVP goals.
