### ISSUE TITLE
Access to Azure's government subscription

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder-technology-and-ux#55]
- Working with NCCS for the path forward.
definition of done
- access to gov azure
- access to bcgov subscription

**Comment by lukegonis** [comment]
Blocked - Waiting for NCCS to provide access

**Comment by bluemel-gov** [comment]
- Re-framing request for access to  Dennis M.

**Comment by bluemel-gov** [comment]
- access has been granted but no access to any subscriptions. Waiting for access

**Comment by bluemel-gov** [comment]
- received approval from management
- Waiting for NCSS for access
