### ISSUE TITLE
Work with OCIO Security to create DNS name for cloud resources

### ISSUE THREAD

**Issue by kelpisland** [bcgov/cloud-pathfinder-technology-and-ux#69]
**Describe the issue**
wildcard certs seem to be an issue with ISB @ the OCIO

**Definition of done**
Get to the bottom of it

**Comment by mumit** [comment]
There are legitimate security concerns around wildcard certs, and security folks usually do not recommend use of wildcard certs as the primary cert solution for enterprises. ISB folks may be focusing on the surface area risk, where a single compromise affects all sub-domains. It would be good to understand what ISB's stance is and why.

**Comment by bluemel-gov** [comment]
- I agree with Mumit and have spoken to Jesse about this.  Him and his team are reviewing the request now.
