### ISSUE TITLE
Resource Email Account for AWS master accounts

### ISSUE THREAD

**Issue by mumit** [bcgov/cloud-pathfinder-technology-and-ux#78]
**Describe the issue**
Need a few email distribution lists for master accounts on aws (and gcp?)

**Which Sprint Priority is this issue related to?**

**Additional context**
This is required for setting up AWS landing zone, which requires unique and non-reusable email addresses

**Definition of done**
Distribution list for AWS EM master, with andy, mumit, shea and todd as members

**Comment by mumit** [comment]
Question: what pattern do we use? Here's a straw dog --- **ocio-cloud-master-<cloud>@gov.bc.ca** where cloud = {aws, azure, gcp, etc}

**Comment by mumit** [comment]
Thought on the pattern -- we'll likely have an EM and another later for enterprise, so would be good to surface that.

Straw dog pattern **ocio-cloud-<cloud>-em-master@gov.bc.ca** where cloud = {aws, azure, gcp, etc}

**Comment by lukegonis** [comment]
Request has been submitted
