### ISSUE TITLE
Create Email Addresses for AWS

### ISSUE THREAD

**Issue by ateppin** [bcgov/cloud-pathfinder-technology-and-ux#86]
The following email addresses need to be created BEFORE the AWS deployment can start

Logging Account:
ocio-aws-em-logging@gov.bc.ca
 
IAM Security Account:
ocio-aws-em-iam-security@gov.bc.ca
 
Ministry Of Health:
ocio-aws-em-moh@gov.bc.ca 
 
** These will need to be created before the landing zone can be deployed.
** If you decide to change the address from the above, please let us know what you end up using.

**Which Sprint Priority is this issue related to?**
sprint 3

**Definition of done**
Email addresses created

**Comment by mumit** [comment]
This may not be needed as we're exploring using aliasing existing a gmail address "bcdevexchange@gmail.com". Let's keep this here until we've reached a conclusion.

**Comment by mumit** [comment]
This is no longer needed. @ateppin @lukegonis - I'm closing this to remove clutter.
